[package]
name = "search-libraries"
description = "An application to search for libraries"
license = "GPL-2.0-only"
version = "0.1.0"
edition = "2021"
authors = ["anhkhoakz"]
repository = "https://github.com/anhkhoakz/search-libraries"
readme = "README.md"
license-file = "LICENSE"


[dependencies]
